name: Deploy Static Portal

on:
  workflow_dispatch:  
  push:
    branches: 
      - master 
      
jobs:
  generate-portal:
    runs-on: ubuntu-latest

    steps:
       
    - uses: actions/checkout@v1
      name : checkout-repo
      id: checkout-repo  
      
    - name: Zip files
      run: zip -qq -r portal-input.zip .
      
    - name: Call build endpoint
      run: curl -X POST --url 'https://www.apimatic.io/api/portal' -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}' -F 'file=@portal-input.zip' -o portal-output.zip
      
    - name: list 
      run: ls
      
    - name: Extract generated Portal
      run: unzip -qq portal-output.zip -d static-portal
      
    - name: list 
      run: ls
      

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: './static-portal'
        production-branch: master
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1
  
    - name: Install api-catalog cli
      run: |
        npm install -g api-catalog-cli@latest
        
    - name: Publish API to Anypoint
      env: 
        ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }} 
        ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
        CATALOG_DESCRIPTOR: './descriptor.yaml' 
        ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORG_ID }}
      run: |
        api-catalog publish-asset -d $CATALOG_DESCRIPTOR --organization="$ANYPOINT_ORG_ID" --username="$ANYPOINT_USERNAME" --password="$ANYPOINT_PASSWORD" --force-update-metadata
